/*
 * Generated by gdbus-codegen 2.38.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "tlm-dbus-login-gen.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.tizen.Tlm.Login
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:TlmDbusLogin
 * @title: TlmDbusLogin
 * @short_description: Generated C code for the org.tizen.Tlm.Login D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-tizen-Tlm-Login.top_of_page">org.tizen.Tlm.Login</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.tizen.Tlm.Login ---- */

static const _ExtendedGDBusArgInfo _tlm_dbus_login_method_info_login_user_IN_ARG_seat_id =
{
  {
    -1,
    (gchar *) "seat_id",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _tlm_dbus_login_method_info_login_user_IN_ARG_username =
{
  {
    -1,
    (gchar *) "username",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _tlm_dbus_login_method_info_login_user_IN_ARG_password =
{
  {
    -1,
    (gchar *) "password",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _tlm_dbus_login_method_info_login_user_IN_ARG_environ =
{
  {
    -1,
    (gchar *) "environ",
    (gchar *) "a{ss}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _tlm_dbus_login_method_info_login_user_IN_ARG_pointers[] =
{
  &_tlm_dbus_login_method_info_login_user_IN_ARG_seat_id,
  &_tlm_dbus_login_method_info_login_user_IN_ARG_username,
  &_tlm_dbus_login_method_info_login_user_IN_ARG_password,
  &_tlm_dbus_login_method_info_login_user_IN_ARG_environ,
  NULL
};

static const _ExtendedGDBusMethodInfo _tlm_dbus_login_method_info_login_user =
{
  {
    -1,
    (gchar *) "loginUser",
    (GDBusArgInfo **) &_tlm_dbus_login_method_info_login_user_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-login-user",
  FALSE
};

static const _ExtendedGDBusArgInfo _tlm_dbus_login_method_info_logout_user_IN_ARG_seat_id =
{
  {
    -1,
    (gchar *) "seat_id",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _tlm_dbus_login_method_info_logout_user_IN_ARG_pointers[] =
{
  &_tlm_dbus_login_method_info_logout_user_IN_ARG_seat_id,
  NULL
};

static const _ExtendedGDBusMethodInfo _tlm_dbus_login_method_info_logout_user =
{
  {
    -1,
    (gchar *) "logoutUser",
    (GDBusArgInfo **) &_tlm_dbus_login_method_info_logout_user_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-logout-user",
  FALSE
};

static const _ExtendedGDBusArgInfo _tlm_dbus_login_method_info_switch_user_IN_ARG_seat_id =
{
  {
    -1,
    (gchar *) "seat_id",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _tlm_dbus_login_method_info_switch_user_IN_ARG_username =
{
  {
    -1,
    (gchar *) "username",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _tlm_dbus_login_method_info_switch_user_IN_ARG_password =
{
  {
    -1,
    (gchar *) "password",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _tlm_dbus_login_method_info_switch_user_IN_ARG_environ =
{
  {
    -1,
    (gchar *) "environ",
    (gchar *) "a{ss}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _tlm_dbus_login_method_info_switch_user_IN_ARG_pointers[] =
{
  &_tlm_dbus_login_method_info_switch_user_IN_ARG_seat_id,
  &_tlm_dbus_login_method_info_switch_user_IN_ARG_username,
  &_tlm_dbus_login_method_info_switch_user_IN_ARG_password,
  &_tlm_dbus_login_method_info_switch_user_IN_ARG_environ,
  NULL
};

static const _ExtendedGDBusMethodInfo _tlm_dbus_login_method_info_switch_user =
{
  {
    -1,
    (gchar *) "switchUser",
    (GDBusArgInfo **) &_tlm_dbus_login_method_info_switch_user_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-switch-user",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _tlm_dbus_login_method_info_pointers[] =
{
  &_tlm_dbus_login_method_info_login_user,
  &_tlm_dbus_login_method_info_logout_user,
  &_tlm_dbus_login_method_info_switch_user,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _tlm_dbus_login_interface_info =
{
  {
    -1,
    (gchar *) "org.tizen.Tlm.Login",
    (GDBusMethodInfo **) &_tlm_dbus_login_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "login",
};


/**
 * tlm_dbus_login_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-tizen-Tlm-Login.top_of_page">org.tizen.Tlm.Login</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
tlm_dbus_login_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_tlm_dbus_login_interface_info.parent_struct;
}

/**
 * tlm_dbus_login_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #TlmDbusLogin interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
tlm_dbus_login_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * TlmDbusLogin:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-tizen-Tlm-Login.top_of_page">org.tizen.Tlm.Login</link>.
 */

/**
 * TlmDbusLoginIface:
 * @parent_iface: The parent interface.
 * @handle_login_user: Handler for the #TlmDbusLogin::handle-login-user signal.
 * @handle_logout_user: Handler for the #TlmDbusLogin::handle-logout-user signal.
 * @handle_switch_user: Handler for the #TlmDbusLogin::handle-switch-user signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-tizen-Tlm-Login.top_of_page">org.tizen.Tlm.Login</link>.
 */

typedef TlmDbusLoginIface TlmDbusLoginInterface;
G_DEFINE_INTERFACE (TlmDbusLogin, tlm_dbus_login, G_TYPE_OBJECT);

static void
tlm_dbus_login_default_init (TlmDbusLoginIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * TlmDbusLogin::handle-login-user:
   * @object: A #TlmDbusLogin.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_seat_id: Argument passed by remote caller.
   * @arg_username: Argument passed by remote caller.
   * @arg_password: Argument passed by remote caller.
   * @arg_environ: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-tizen-Tlm-Login.loginUser">loginUser()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call tlm_dbus_login_complete_login_user() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-login-user",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (TlmDbusLoginIface, handle_login_user),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    5,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_VARIANT);

  /**
   * TlmDbusLogin::handle-logout-user:
   * @object: A #TlmDbusLogin.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_seat_id: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-tizen-Tlm-Login.logoutUser">logoutUser()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call tlm_dbus_login_complete_logout_user() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-logout-user",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (TlmDbusLoginIface, handle_logout_user),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * TlmDbusLogin::handle-switch-user:
   * @object: A #TlmDbusLogin.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_seat_id: Argument passed by remote caller.
   * @arg_username: Argument passed by remote caller.
   * @arg_password: Argument passed by remote caller.
   * @arg_environ: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-tizen-Tlm-Login.switchUser">switchUser()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call tlm_dbus_login_complete_switch_user() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-switch-user",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (TlmDbusLoginIface, handle_switch_user),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    5,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_VARIANT);

}

/**
 * tlm_dbus_login_call_login_user:
 * @proxy: A #TlmDbusLoginProxy.
 * @arg_seat_id: Argument to pass with the method invocation.
 * @arg_username: Argument to pass with the method invocation.
 * @arg_password: Argument to pass with the method invocation.
 * @arg_environ: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-tizen-Tlm-Login.loginUser">loginUser()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call tlm_dbus_login_call_login_user_finish() to get the result of the operation.
 *
 * See tlm_dbus_login_call_login_user_sync() for the synchronous, blocking version of this method.
 */
void
tlm_dbus_login_call_login_user (
    TlmDbusLogin *proxy,
    const gchar *arg_seat_id,
    const gchar *arg_username,
    const gchar *arg_password,
    GVariant *arg_environ,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "loginUser",
    g_variant_new ("(sss@a{ss})",
                   arg_seat_id,
                   arg_username,
                   arg_password,
                   arg_environ),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * tlm_dbus_login_call_login_user_finish:
 * @proxy: A #TlmDbusLoginProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to tlm_dbus_login_call_login_user().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with tlm_dbus_login_call_login_user().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
tlm_dbus_login_call_login_user_finish (
    TlmDbusLogin *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * tlm_dbus_login_call_login_user_sync:
 * @proxy: A #TlmDbusLoginProxy.
 * @arg_seat_id: Argument to pass with the method invocation.
 * @arg_username: Argument to pass with the method invocation.
 * @arg_password: Argument to pass with the method invocation.
 * @arg_environ: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-tizen-Tlm-Login.loginUser">loginUser()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See tlm_dbus_login_call_login_user() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
tlm_dbus_login_call_login_user_sync (
    TlmDbusLogin *proxy,
    const gchar *arg_seat_id,
    const gchar *arg_username,
    const gchar *arg_password,
    GVariant *arg_environ,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "loginUser",
    g_variant_new ("(sss@a{ss})",
                   arg_seat_id,
                   arg_username,
                   arg_password,
                   arg_environ),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * tlm_dbus_login_call_logout_user:
 * @proxy: A #TlmDbusLoginProxy.
 * @arg_seat_id: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-tizen-Tlm-Login.logoutUser">logoutUser()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call tlm_dbus_login_call_logout_user_finish() to get the result of the operation.
 *
 * See tlm_dbus_login_call_logout_user_sync() for the synchronous, blocking version of this method.
 */
void
tlm_dbus_login_call_logout_user (
    TlmDbusLogin *proxy,
    const gchar *arg_seat_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "logoutUser",
    g_variant_new ("(s)",
                   arg_seat_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * tlm_dbus_login_call_logout_user_finish:
 * @proxy: A #TlmDbusLoginProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to tlm_dbus_login_call_logout_user().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with tlm_dbus_login_call_logout_user().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
tlm_dbus_login_call_logout_user_finish (
    TlmDbusLogin *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * tlm_dbus_login_call_logout_user_sync:
 * @proxy: A #TlmDbusLoginProxy.
 * @arg_seat_id: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-tizen-Tlm-Login.logoutUser">logoutUser()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See tlm_dbus_login_call_logout_user() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
tlm_dbus_login_call_logout_user_sync (
    TlmDbusLogin *proxy,
    const gchar *arg_seat_id,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "logoutUser",
    g_variant_new ("(s)",
                   arg_seat_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * tlm_dbus_login_call_switch_user:
 * @proxy: A #TlmDbusLoginProxy.
 * @arg_seat_id: Argument to pass with the method invocation.
 * @arg_username: Argument to pass with the method invocation.
 * @arg_password: Argument to pass with the method invocation.
 * @arg_environ: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-tizen-Tlm-Login.switchUser">switchUser()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call tlm_dbus_login_call_switch_user_finish() to get the result of the operation.
 *
 * See tlm_dbus_login_call_switch_user_sync() for the synchronous, blocking version of this method.
 */
void
tlm_dbus_login_call_switch_user (
    TlmDbusLogin *proxy,
    const gchar *arg_seat_id,
    const gchar *arg_username,
    const gchar *arg_password,
    GVariant *arg_environ,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "switchUser",
    g_variant_new ("(sss@a{ss})",
                   arg_seat_id,
                   arg_username,
                   arg_password,
                   arg_environ),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * tlm_dbus_login_call_switch_user_finish:
 * @proxy: A #TlmDbusLoginProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to tlm_dbus_login_call_switch_user().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with tlm_dbus_login_call_switch_user().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
tlm_dbus_login_call_switch_user_finish (
    TlmDbusLogin *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * tlm_dbus_login_call_switch_user_sync:
 * @proxy: A #TlmDbusLoginProxy.
 * @arg_seat_id: Argument to pass with the method invocation.
 * @arg_username: Argument to pass with the method invocation.
 * @arg_password: Argument to pass with the method invocation.
 * @arg_environ: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-tizen-Tlm-Login.switchUser">switchUser()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See tlm_dbus_login_call_switch_user() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
tlm_dbus_login_call_switch_user_sync (
    TlmDbusLogin *proxy,
    const gchar *arg_seat_id,
    const gchar *arg_username,
    const gchar *arg_password,
    GVariant *arg_environ,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "switchUser",
    g_variant_new ("(sss@a{ss})",
                   arg_seat_id,
                   arg_username,
                   arg_password,
                   arg_environ),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * tlm_dbus_login_complete_login_user:
 * @object: A #TlmDbusLogin.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-tizen-Tlm-Login.loginUser">loginUser()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
tlm_dbus_login_complete_login_user (
    TlmDbusLogin *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * tlm_dbus_login_complete_logout_user:
 * @object: A #TlmDbusLogin.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-tizen-Tlm-Login.logoutUser">logoutUser()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
tlm_dbus_login_complete_logout_user (
    TlmDbusLogin *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * tlm_dbus_login_complete_switch_user:
 * @object: A #TlmDbusLogin.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-tizen-Tlm-Login.switchUser">switchUser()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
tlm_dbus_login_complete_switch_user (
    TlmDbusLogin *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * TlmDbusLoginProxy:
 *
 * The #TlmDbusLoginProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * TlmDbusLoginProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #TlmDbusLoginProxy.
 */

struct _TlmDbusLoginProxyPrivate
{
  GData *qdata;
};

static void tlm_dbus_login_proxy_iface_init (TlmDbusLoginIface *iface);

G_DEFINE_TYPE_WITH_CODE (TlmDbusLoginProxy, tlm_dbus_login_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (TlmDbusLoginProxy)
                         G_IMPLEMENT_INTERFACE (TLM_DBUS_TYPE_LOGIN, tlm_dbus_login_proxy_iface_init));

static void
tlm_dbus_login_proxy_finalize (GObject *object)
{
  TlmDbusLoginProxy *proxy = TLM_DBUS_LOGIN_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (tlm_dbus_login_proxy_parent_class)->finalize (object);
}

static void
tlm_dbus_login_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
tlm_dbus_login_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
tlm_dbus_login_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_tlm_dbus_login_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TLM_DBUS_TYPE_LOGIN);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TLM_DBUS_TYPE_LOGIN);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
tlm_dbus_login_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  TlmDbusLoginProxy *proxy = TLM_DBUS_LOGIN_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_tlm_dbus_login_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_tlm_dbus_login_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
tlm_dbus_login_proxy_init (TlmDbusLoginProxy *proxy)
{
  proxy->priv = tlm_dbus_login_proxy_get_instance_private (proxy);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), tlm_dbus_login_interface_info ());
}

static void
tlm_dbus_login_proxy_class_init (TlmDbusLoginProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = tlm_dbus_login_proxy_finalize;
  gobject_class->get_property = tlm_dbus_login_proxy_get_property;
  gobject_class->set_property = tlm_dbus_login_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = tlm_dbus_login_proxy_g_signal;
  proxy_class->g_properties_changed = tlm_dbus_login_proxy_g_properties_changed;

}

static void
tlm_dbus_login_proxy_iface_init (TlmDbusLoginIface *iface)
{
}

/**
 * tlm_dbus_login_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-tizen-Tlm-Login.top_of_page">org.tizen.Tlm.Login</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call tlm_dbus_login_proxy_new_finish() to get the result of the operation.
 *
 * See tlm_dbus_login_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
tlm_dbus_login_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TLM_DBUS_TYPE_LOGIN_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.tizen.Tlm.Login", NULL);
}

/**
 * tlm_dbus_login_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to tlm_dbus_login_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with tlm_dbus_login_proxy_new().
 *
 * Returns: (transfer full) (type TlmDbusLoginProxy): The constructed proxy object or %NULL if @error is set.
 */
TlmDbusLogin *
tlm_dbus_login_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return TLM_DBUS_LOGIN (ret);
  else
    return NULL;
}

/**
 * tlm_dbus_login_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-tizen-Tlm-Login.top_of_page">org.tizen.Tlm.Login</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See tlm_dbus_login_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type TlmDbusLoginProxy): The constructed proxy object or %NULL if @error is set.
 */
TlmDbusLogin *
tlm_dbus_login_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TLM_DBUS_TYPE_LOGIN_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.tizen.Tlm.Login", NULL);
  if (ret != NULL)
    return TLM_DBUS_LOGIN (ret);
  else
    return NULL;
}


/**
 * tlm_dbus_login_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like tlm_dbus_login_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call tlm_dbus_login_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See tlm_dbus_login_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
tlm_dbus_login_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TLM_DBUS_TYPE_LOGIN_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.tizen.Tlm.Login", NULL);
}

/**
 * tlm_dbus_login_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to tlm_dbus_login_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with tlm_dbus_login_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type TlmDbusLoginProxy): The constructed proxy object or %NULL if @error is set.
 */
TlmDbusLogin *
tlm_dbus_login_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return TLM_DBUS_LOGIN (ret);
  else
    return NULL;
}

/**
 * tlm_dbus_login_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like tlm_dbus_login_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See tlm_dbus_login_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type TlmDbusLoginProxy): The constructed proxy object or %NULL if @error is set.
 */
TlmDbusLogin *
tlm_dbus_login_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TLM_DBUS_TYPE_LOGIN_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.tizen.Tlm.Login", NULL);
  if (ret != NULL)
    return TLM_DBUS_LOGIN (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * TlmDbusLoginSkeleton:
 *
 * The #TlmDbusLoginSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * TlmDbusLoginSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #TlmDbusLoginSkeleton.
 */

struct _TlmDbusLoginSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_tlm_dbus_login_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  TlmDbusLoginSkeleton *skeleton = TLM_DBUS_LOGIN_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TLM_DBUS_TYPE_LOGIN);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TLM_DBUS_TYPE_LOGIN);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_tlm_dbus_login_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  TlmDbusLoginSkeleton *skeleton = TLM_DBUS_LOGIN_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_tlm_dbus_login_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_tlm_dbus_login_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  TlmDbusLoginSkeleton *skeleton = TLM_DBUS_LOGIN_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_tlm_dbus_login_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _tlm_dbus_login_skeleton_vtable =
{
  _tlm_dbus_login_skeleton_handle_method_call,
  _tlm_dbus_login_skeleton_handle_get_property,
  _tlm_dbus_login_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
tlm_dbus_login_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return tlm_dbus_login_interface_info ();
}

static GDBusInterfaceVTable *
tlm_dbus_login_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_tlm_dbus_login_skeleton_vtable;
}

static GVariant *
tlm_dbus_login_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  TlmDbusLoginSkeleton *skeleton = TLM_DBUS_LOGIN_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_tlm_dbus_login_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _tlm_dbus_login_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _tlm_dbus_login_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _tlm_dbus_login_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.tizen.Tlm.Login", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
tlm_dbus_login_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void tlm_dbus_login_skeleton_iface_init (TlmDbusLoginIface *iface);
G_DEFINE_TYPE_WITH_CODE (TlmDbusLoginSkeleton, tlm_dbus_login_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (TlmDbusLoginSkeleton)
                         G_IMPLEMENT_INTERFACE (TLM_DBUS_TYPE_LOGIN, tlm_dbus_login_skeleton_iface_init));

static void
tlm_dbus_login_skeleton_finalize (GObject *object)
{
  TlmDbusLoginSkeleton *skeleton = TLM_DBUS_LOGIN_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (tlm_dbus_login_skeleton_parent_class)->finalize (object);
}

static void
tlm_dbus_login_skeleton_init (TlmDbusLoginSkeleton *skeleton)
{
  skeleton->priv = tlm_dbus_login_skeleton_get_instance_private (skeleton);
  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
tlm_dbus_login_skeleton_class_init (TlmDbusLoginSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = tlm_dbus_login_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = tlm_dbus_login_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = tlm_dbus_login_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = tlm_dbus_login_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = tlm_dbus_login_skeleton_dbus_interface_get_vtable;
}

static void
tlm_dbus_login_skeleton_iface_init (TlmDbusLoginIface *iface)
{
}

/**
 * tlm_dbus_login_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-tizen-Tlm-Login.top_of_page">org.tizen.Tlm.Login</link>.
 *
 * Returns: (transfer full) (type TlmDbusLoginSkeleton): The skeleton object.
 */
TlmDbusLogin *
tlm_dbus_login_skeleton_new (void)
{
  return TLM_DBUS_LOGIN (g_object_new (TLM_DBUS_TYPE_LOGIN_SKELETON, NULL));
}

